### ISSUE TITLE
Assignment expression doesn't have value.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire-2#15]
This code prints out 'U' (that's not the expected result):

```
def mod(x, n)
    q = x / n
    p = q * n
    m = x - p

def putchar(c)
    as "out r1"

putchar(48 + mod(11, 2))
```

Yet using statement that at the first peek has no effect is apparently setting the return value:

```
def mod(x, n)
    q = x / n
    p = q * n
    m = x - p
    m

def putchar(c)
    as "out r1"

putchar(48 + mod(11, 2))
```

... dumps out 1 (expected result)

**Comment by maviek** [comment]
Assignment expression assigns the address of the variable to **r1**. In this example, the address of the variable **m** is 37 (32 + 5), so 48 + 37 gives 85 / 'U'.

**Comment by KrzysztofSzewczyk** [comment]
Assignment expression should return left-hand side, not address. Please don't create new JavaScript
