### ISSUE TITLE
Sapphire doesn't error when function body is not found

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire-2#57]
Referencing #16, the issue is still relevant as no error is thrown. Original text:

```
So this boils down to simple problem:

def putchar()
    as "out 48"

def putcharw()
    putchar()

putcharw()

This should print out 48, yet it doesn't.
```

**Comment by maviek** [comment]
No, it shouldn't print out 48. `putchar` is global, when putchar in `putcharw` is local. You must tell the compiler that putchar is global.
